name: Leela
description: Leela. The Game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_bloc: ^8.1.3
  gif: 2.2.0
#  flame: ^1.7.3
  lottie: ^2.4.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-regular.ttf
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lotties/
    - assets/images/game/background/